#!/usr/bin/env python3
from pathlib import Path
import argparse, re
from difflib import SequenceMatcher

MIN_EXACT=140
MIN_NEAR=220
NEAR_RATIO=0.94


def normalize(s): return re.sub(r'\s+',' ',s.strip()).lower()

def paragraphs(path):
    text=path.read_text(encoding='utf-8')
    out=[]
    for block in re.split(r'\n\s*\n',text):
        n=normalize(block)
        if not n or n.startswith('---') or 'generated by tools/sync_profiles.py' in n: continue
        if n.startswith('# ') or n.startswith('## '): continue
        out.append((block.strip(),n))
    return out

def canonical_files(root):
    files=[root/'global/AGENTS.codex.md',root/'profiles/personal/AGENTS.md']
    files += sorted((root/'.agents/skills').glob('*/SKILL.md'))
    files += [root/'docs/system/QUALITY_PROTOCOL.md',root/'docs/system/TOOL_ROUTING.md',root/'docs/system/HANDOFF_PROTOCOL.md',root/'docs/system/CHANGE_CONTROL.md']
    return [p for p in files if p.is_file()]

def validate(root):
    errors=[]; paras=[]
    for p in canonical_files(root):
        for raw,n in paragraphs(p): paras.append((p,n,raw))
    seen={}
    for p,n,raw in paras:
        if len(n)<MIN_EXACT: continue
        if n in seen and seen[n]!=p:
            errors.append(f'exact canonical paragraph duplication: {seen[n].relative_to(root)} <-> {p.relative_to(root)} :: {raw[:100]}')
        else: seen[n]=p
    # Near-duplicate guard only for long paragraphs and different owner files.
    long=[x for x in paras if len(x[1])>=MIN_NEAR]
    for i,(p1,n1,r1) in enumerate(long):
        for p2,n2,r2 in long[i+1:]:
            if p1==p2 or abs(len(n1)-len(n2)) > max(len(n1),len(n2))*0.18: continue
            ratio=SequenceMatcher(None,n1,n2,autojunk=True).ratio()
            if ratio>=NEAR_RATIO:
                errors.append(f'near-duplicate canonical paragraphs ({ratio:.2f}): {p1.relative_to(root)} <-> {p2.relative_to(root)}')
    return errors

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--root',default='.'); a=ap.parse_args(); root=Path(a.root).resolve(); errors=validate(root)
    for x in errors: print('ERROR:',x)
    if errors: print(f'DUPLICATION AUDIT: FAIL ({len(errors)} errors)'); return 1
    print('DUPLICATION AUDIT: PASS'); return 0
if __name__=='__main__': raise SystemExit(main())
