from __future__ import annotations
from pathlib import Path
import shutil

RUNTIME_DIR = '.progressive'

TEXT_REPLACEMENTS = [
    ('docs/project/', '.progressive/project/'),
    ('docs/phases/', '.progressive/phases/'),
    ('docs/completions/', '.progressive/completions/'),
    ('docs/decisions/', '.progressive/decisions/'),
    ('docs/system/', '.progressive/system/'),
    ('prompts/', '.progressive/prompts/'),
    ('templates/', '.progressive/templates/'),
    ('integrations/', '.progressive/integrations/'),
    ('tools/', '.progressive/tools/'),
]

SYSTEM_RUNTIME = [
    'CONTEXT_PROTOCOL.md',
    'HANDOFF_PROTOCOL.md',
    'LAYER_OWNERSHIP.md',
    'QUALITY_PROTOCOL.md',
    'TOOL_ROUTING.md',
]

RUNTIME_TOOLS = {
    'common.py': 'common.py',
    'context_compile.py': 'context_compile.py',
    'context_report.py': 'context_report.py',
    'runtime_audit.py': 'audit.py',
    'tooling_status.py': 'tooling_status.py',
    'tooling_bootstrap.py': 'tooling_bootstrap.py',
}

PROJECT_SEEDS = [
    'ARCHITECTURE.md',
    'CONTEXT_MANIFEST.json',
    'NEXT_SESSION.md',
    'PROJECT_BRIEF.md',
    'ROADMAP.md',
    'TOOLING_STATUS.json',
    'TOOLING_STATUS.md',
]


def transform_text(text: str) -> str:
    # Protect already-runtime paths so source docs may mention both layouts safely.
    text = text.replace('.progressive/', '__PC_RUNTIME__/')
    for old, new in TEXT_REPLACEMENTS:
        text = text.replace(old, new)
    return text.replace('__PC_RUNTIME__/', '.progressive/')


def write_text_transformed(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(transform_text(src.read_text(encoding='utf-8')), encoding='utf-8')


def copy_tree_transformed(src: Path, dst: Path) -> None:
    for p in src.rglob('*'):
        if not p.is_file():
            continue
        out = dst / p.relative_to(src)
        try:
            write_text_transformed(p, out)
        except UnicodeDecodeError:
            out.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(p, out)


def render_agent_profile(root: Path, profile: str) -> str:
    text = transform_text((root / 'profiles' / profile / 'AGENTS.md').read_text(encoding='utf-8'))
    if profile == 'standalone':
        text = text.replace('# Progressive Context Spec Kit — Standalone Profile', '# Progressive Context Spec Kit — Project Runtime')
        lines = []
        for line in text.splitlines():
            if line.startswith('<!-- GENERATED by '):
                lines.append('<!-- Generated from Framework Source; do not edit the framework-owned prefix directly. -->')
            else:
                lines.append(line)
        text = '\n'.join(lines) + ('\n' if text.endswith('\n') else '')
    return text

def runtime_entries(root: Path, profile: str = 'standalone'):
    """Return (source, destination-relative, transform_text) entries for Project Runtime."""
    entries = []
    # Root agent entrypoints. Standalone is the zero-setup default release profile.
    entries.append((root / 'profiles' / profile / 'AGENTS.md', Path('AGENTS.md'), True))
    entries.append((root / 'CLAUDE.md', Path('CLAUDE.md'), True))

    # Native agent Skills remain in their platform-standard hidden locations.
    for base in ['.agents/skills', '.claude/skills']:
        for p in (root / base).rglob('*'):
            if p.is_file(): entries.append((p, Path(base) / p.relative_to(root / base), True))

    # Canonical project state lives under one hidden framework directory.
    for name in PROJECT_SEEDS:
        p = root / 'docs/project' / name
        if p.is_file(): entries.append((p, Path(RUNTIME_DIR) / 'project' / name, True))

    # Runtime protocols only. Framework development/eval/migration docs stay source-only.
    for name in SYSTEM_RUNTIME:
        p = root / 'docs/system' / name
        if p.is_file(): entries.append((p, Path(RUNTIME_DIR) / 'system' / name, True))

    # Prompts/templates/tool adapters stay available but hidden from normal project browsing.
    for source_dir, runtime_subdir in [
        ('prompts', 'prompts'),
        ('templates', 'templates'),
        ('integrations', 'integrations'),
    ]:
        for p in (root / source_dir).rglob('*'):
            if p.is_file(): entries.append((p, Path(RUNTIME_DIR) / runtime_subdir / p.relative_to(root / source_dir), True))

    for source_name, runtime_name in RUNTIME_TOOLS.items():
        p = root / 'tools' / source_name
        if p.is_file(): entries.append((p, Path(RUNTIME_DIR) / 'tools' / runtime_name, False))

    # License/notice are kept hidden with framework internals rather than polluting product root.
    for name in ['LICENSE', 'NOTICE.md']:
        p = root / name
        if p.is_file(): entries.append((p, Path(RUNTIME_DIR) / name, False))
    return entries


def write_runtime(root: Path, target: Path, profile: str = 'standalone', agent: str = 'both') -> None:
    target.mkdir(parents=True, exist_ok=True)
    for src, rel, transform in runtime_entries(root, profile):
        dst = target / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        if rel.as_posix() == 'AGENTS.md':
            dst.write_text(render_agent_profile(root, profile), encoding='utf-8')
        elif transform:
            write_text_transformed(src, dst)
        else:
            shutil.copy2(src, dst)
    meta = target / RUNTIME_DIR
    version = (root / 'VERSION').read_text(encoding='utf-8').strip()
    (meta / 'VERSION').write_text(version + '\n', encoding='utf-8')
    (meta / 'PROFILE').write_text(profile + '\n', encoding='utf-8')
    (meta / 'AGENT_TARGET').write_text(agent + '\n', encoding='utf-8')
    (meta / 'ADOPTION_STATE').write_text('ready\n', encoding='utf-8')
    (meta / 'phases').mkdir(exist_ok=True)
    (meta / 'completions').mkdir(exist_ok=True)
    (meta / 'decisions').mkdir(exist_ok=True)
