#!/usr/bin/env python3
from pathlib import Path
import argparse

SEPARATOR="\n\n---\n\n"
HEADER="# Progressive Context Kit — Standalone Profile\n\n<!-- GENERATED by tools/sync_profiles.py from global/AGENTS.codex.md + profiles/personal/AGENTS.md. Do not edit directly. -->\n\n"
PROJECT_SENTINEL="\n\n<!-- PROJECT-SPECIFIC-INSTRUCTIONS -->\n\n"

def compose(root):
    g=(root/'global/AGENTS.codex.md').read_text(encoding='utf-8').strip(); p=(root/'profiles/personal/AGENTS.md').read_text(encoding='utf-8').strip(); return HEADER+g+SEPARATOR+p+'\n'

def active_profile(root):
    p=root/'.progressive-context-spec-kit/PROFILE'
    if p.is_file() and p.read_text(encoding='utf-8').strip() in {'personal','standalone'}: return p.read_text(encoding='utf-8').strip()
    return 'personal'

def expected_text(root,profile): return (root/'profiles'/profile/'AGENTS.md').read_text(encoding='utf-8')

def split_project_specific(text):
    if PROJECT_SENTINEL in text:
        base,suffix=text.split(PROJECT_SENTINEL,1); return base.rstrip()+'\n',suffix
    return text,''

def root_matches_profile(root,profile):
    p=root/'AGENTS.md'
    if not p.is_file(): return False
    base,_=split_project_specific(p.read_text(encoding='utf-8'))
    return base.rstrip()==expected_text(root,profile).rstrip()

def render_root(root,profile,existing=''):
    _,suffix=split_project_specific(existing)
    base=expected_text(root,profile).rstrip()+'\n'
    return base+(PROJECT_SENTINEL+suffix if suffix else '')

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--root',default='.'); ap.add_argument('--apply',action='store_true'); a=ap.parse_args(); root=Path(a.root).resolve(); standalone=root/'profiles/standalone/AGENTS.md'; root_agents=root/'AGENTS.md'; profile=active_profile(root); expected=compose(root)
    if a.apply:
        standalone.parent.mkdir(parents=True,exist_ok=True); standalone.write_text(expected,encoding='utf-8')
        existing=root_agents.read_text(encoding='utf-8') if root_agents.is_file() else ''
        root_agents.write_text(render_root(root,profile,existing),encoding='utf-8'); print(f'profiles synchronized (active={profile})'); return 0
    problems=[]
    current = standalone.read_text(encoding='utf-8') if standalone.is_file() else ''
    if current != expected: problems.append('profiles/standalone/AGENTS.md is not generated composition')
    if not root_matches_profile(root,profile): problems.append(f'root AGENTS.md does not contain active {profile} profile as canonical prefix')
    if problems:
        [print('ERROR:',x) for x in problems]; print('Run: python3 tools/sync_profiles.py --apply'); return 1
    print(f'profiles: PASS (active={profile})'); return 0
if __name__=='__main__': raise SystemExit(main())
